### ISSUE TITLE
Tasks before new release V1

### ISSUE THREAD

**Issue by BenjMy** [agrogeophy/catalog#3]
Tasks before new release (V1, publicly available and broadly advertised): 

- [x] migration of the website to a github page for secure connection (full static prototype can be viewed at: https://github.com/sagitta1618/agrogeophy-catalog)
- [x] remove and replace php queries and mysql database by jam stack procedure based on a simple csv table. This will facilitate user contribution and management of the catalog. 
- [x] use CI integration on github catalog to update the map and tables -> GB: not needed, just changing the CSV will automatically update the tables and map
- [x] new logo integration
- [x] discuss integration within 2i2c -> GB: I don't think we need it for now, using free binder would already be good I think
- [x] find a way to upload files (notebook, cover image, dataset), either using Github merge request (GB like that) or using Google Form? as the JAMStack, doesn't handle file upload using PHP
- [x] decide wether we keep the database (a) in a single .csv or (b) we split it in different table (relational database) - GB vote for keeping it all in a single CSV for easier maintenance
- [x] add github action to build the documentation examples (gallery of notebook) and integrate them into the main website using sphinx?
- [x] green map marker now shown
- [x] test db update with new contributions
- [x] try the specific case of notebook submission
- [x] fix DOI link issue, altimetric donuts
- [x] fix cover_picture contribution detailed

**Comment by sagitta1618** [comment]
If you have other tasks in mind, please edit the main comment. I'll open specific issue for some of them to keep things tidy.

**Comment by sagitta1618** [comment]
@BenjMy also the altimetric donuts doesn't show up. I don't know if we need to included a script on the page as well.

**Comment by BenjMy** [comment]
Hi @sagitta1618 . Can you give me the contribution id for which the altimetric donuts doesn't show p ?

**Comment by sagitta1618** [comment]
Quite a few actually. for instance: https://agrogeophy.github.io/catalog/contribution_details.html?id=6

**Comment by BenjMy** [comment]
- altimetric donuts: the problem depends on the browser. Altmetrics doesn't show up using Firefox but it is working with Chrome.
- green marker cluster type removed (not active for a certain zoom position which in a way solved the issue)

**Comment by sagitta1618** [comment]
All good then! All tasks are completed for v1.0.0 :)
