### ISSUE TITLE
inconsistent columns naming

### ISSUE THREAD

**Issue by sagitta1618** [agrogeophy/catalog#7]
In the database (.csv file), in the submission form (input_form.html) and in the details (contribution_details.html), there is inconsistent naming between the field. e.g. SpatialScale, spatial_scale, spatialScale, SpatialScale_new

I recommend we formalize on camelCase or underscore like (avoiding space and hence allowing sharing same id and name field with the database headers).

Also I suggest we delete unused columns of the database related to Zhao et al. and not queried at all.

This change will imply editing the db.csv, input_form.html, contribution_details.html and catalog.html

@BenjMy let me know what you think

**Comment by sagitta1618** [comment]
We should also update the database structure markdown file

**Comment by sagitta1618** [comment]
proposed update to the database columns (in this specific order):

id
surname
name
organisation
email
contribution_type
title
cover_picture
publication_date
publication_link
authors
keywords
latitude
longitude
method
spatial_scale
temporal_scale
temperature_correction
instrument
dimension
permanent_setup
software_name
software_licence
plant
organ
soil
water
ancillary_data
dataset_link
dataset_license
dataset_comment
comment

DELETE Sequence
DELETE Nb of electrodes
DELETE Borehole
DELETE rhizotron
DELETE method
DELETE boundary cond
DELETE spatial scale (m)
DELETE prospection date
DELETE calibration
DELETE website
DELETE software website


This way it will follow the online input form. Also I suggest we update the `input_form.html` to remove systematic comment after each section (or we add fields to the database for them) and remove the file upload and notebook upload as those should be attached to the mailto manually by the contributor.

**Comment by BenjMy** [comment]
Systematic comments after each section were part of the continuous improvement of metadata schema (if some are missings then the user is free to enter a new one). If we choose to remove them we need a plan to provide free inputs for new metadata. 

I suggest creating a link to open an issue on GitHub when missing entries in the input form. See https://github.com/agrogeophy/catalog/issues/6#issue-782028345

For each catalog release, we update the metadata entries.

**Comment by sagitta1618** [comment]
For a given `<select>` tag, the select jQuery plugin will be used such that if the user don't find a choice, it can still write down its own choice. One big comment section will be kept at the end of the form (and integrated in the db.csv as `comment` column). Additionnaly a link to a github issue will be provided for continuous improvement of the form.
