### ISSUE TITLE
sql.js for relational database

### ISSUE THREAD

**Issue by sagitta1618** [agrogeophy/catalog#8]
While I am not totally convinced that a relational database will be very useful given the size of the project (even if we have thousands lines, a .csv will still be a few kb).

If there is incentive to use relational SQL database on the client side, the [sql.js](https://sql.js.org) framework can be well adapted.

@BenjMy if we keep the .csv (which I think it's ok), we can close the issue for info.

**Comment by sagitta1618** [comment]
so it means we could replace the .csv by a .sqlite file that will be processed client-side using javascript (sql.js)

**Comment by BenjMy** [comment]
Ok let's keep the .csv file for simplicity. 
I close the issue.
